engines:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc
  duplication:
    enabled: false
ratings:
   paths:
   - "*.js"
   - "src/**.js"
exclude_paths:
- "docs/"
- "node_modules/"
